### ISSUE TITLE
규제샌드박스 제안 준비

### ISSUE THREAD

**Issue by number00** [hkmc-airlab/common-operation#1]
> 규제샌드박스 8/말 제안을 목표로, 규제샌드박스 신청서 작성을 진행하고자 합니다.
우선 첨부로 드린 기준으로 KSTM과의 작성 R&R으로 진행하기로 했습니다. (김재관 과장하고 금일 유선 논의)

초안 **1차 마감 일정은 차주 수요일**로 설정했습니다.

> 1차 초안 완료되면 합본으로 실무협의하고 보완한 후, 2차 초안을 가지고
NIPA 정보통신산업진흥원에 1차 제출할 예정입니다.(8/19일주
NIPA와의 자료 컨설팅 진행하고 3차 수정 진행 후 최종 과기부로 최종 제출하는 프로세스로 진행될 예정입니다.

현대차에서 작성 필요한 부분도 서비스 기술/기획 내용이 들어가야하는 부분은 AIR랩,
그 이외 부분은 모빌리티사업1팀에서 작성하는 것으로 제안드립니다. 

> - AIR랩 : 1.가. / 3.가. / 3나. / 3.다. / 4
> - 모빌리티사업1팀 : 6.가. / 7.가. / 7.나. / 신청기관 현황자료

**Comment by maiden84** [comment]
8/21 규제샌드박스 회의 자료 : 에어랩
[규제샌드박스_초안_에어랩(보안해제).docx](https://github.com/hkmc-airlab/common-operation/files/3523623/_._.docx)

**Comment by Jaegwan-KIM** [comment]
정규홍 대표님 계정 추가 요청드립니다. @number00 
- chungkyuhong@gmail.com

**Comment by number00** [comment]
@Jaegwan-KIM Github 가입 하셨는 지 확인 바랍니다. (해당메일로 사용자가 안나옵니다)
가입 후 ID 알려주세요.

**Comment by Jaegwan-KIM** [comment]
정규홍 대표님
ID: chungkyuhong
로 부탁드립니다.

**Comment by number00** [comment]
초대했습니다.

**Comment by maiden84** [comment]
#10 으로 연결해서 진행
