### ISSUE TITLE
실증특례 신청서 및 참고자료

### ISSUE THREAD

**Issue by Jaegwan-KIM** [hkmc-airlab/common-operation#8]
각사별 신청서 작성 자료 공유 및 참고자료 공유

**Comment by Jaegwan-KIM** [comment]
- 대중교통 취약지로서의 상암 관련 보도자료
http://news.jtbc.joins.com/article/article.aspx?news_id=NB11540098
http://www.fnnews.com/news/201711281023599225

<카카오모빌리티 보고서 2017년 자료>
[2017 kakaomobility report.pdf](https://github.com/hkmc-airlab/common-operation/files/3524475/2017.kakaomobility.report.pdf)
 : 상암 지역 이외에 대중교통 취약지역에 대한 자료 참고하시면 도움이 될 것 같습니다.

**Comment by maiden84** [comment]
감사합니다. 신청서에 반영완료
